In [1]:
!pip install pyarrow 
!pip install sqlparse

Requirement already satisfied: pyarrow in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pyarrow) (1.19.2)
Collecting sqlparse
  Downloading sqlparse-0.4.2-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.6 MB/s  eta 0:00:01
Installing collected packages: sqlparse
Successfully installed sqlparse-0.4.2

In [2]:
!pip install --upgrade --user  ibmcloudsql

Collecting ibmcloudsql
  Downloading ibmcloudsql-0.5.2.tar.gz (54 kB)
     |████████████████████████████████| 54 kB 5.3 MB/s  eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pandas>=1.1.0 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (1.2.4)
Requirement already satisfied: pyarrow in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (3.0.0)
Collecting pre-commit
  Downloading pre_commit-2.17.0-py2.py3-none-any.whl (195 kB)
     |████████████████████████████████| 195 kB 29.6 MB/s eta 0:00:01
Requirement already satisfied: numpy in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (1.19.2)
Requirement already satisfied: packaging in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (20.9)
Collecting ibm-cos-sdk-core==2.10.0
  Downloading ibm-cos-sdk-core-2.10.0.tar.gz (888 kB)
     |████████████████████████████████| 888 kB 55.1 MB/s eta 0:00:01
Collecting ibm-cos-sdk==2.10.0
  Downloading ibm-cos-sdk-2.10.0.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 3.8 MB/s  eta 0:00:01
Requirement already satisfied: sqlparse>=0.4.2 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (0.4.2)
Requirement already satisfied: importlib-metadata in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (3.10.0)
Requirement already satisfied: python-dateutil in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (2.8.1)
Collecting backoff==1.10.0
  Downloading backoff-1.10.0-py2.py3-none-any.whl (31 kB)
Collecting isodate
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 1.7 MB/s  eta 0:00:01
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: requests>=2.2.0 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (2.25.1)
Requirement already satisfied: typing-extensions in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibmcloudsql) (3.7.4.3)
Collecting ibm-cos-sdk-s3transfer==2.10.0
  Downloading ibm-cos-sdk-s3transfer-2.10.0.tar.gz (133 kB)
     |████████████████████████████████| 133 kB 20.3 MB/s eta 0:00:01
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibm-cos-sdk==2.10.0->ibmcloudsql) (0.10.0)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pandas>=1.1.0->ibmcloudsql) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from python-dateutil->ibmcloudsql) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests>=2.2.0->ibmcloudsql) (1.26.6)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests>=2.2.0->ibmcloudsql) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests>=2.2.0->ibmcloudsql) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from requests>=2.2.0->ibmcloudsql) (2.8)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from deprecated->ibmcloudsql) (1.12.1)
Requirement already satisfied: zipp>=0.5 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from importlib-metadata->ibmcloudsql) (3.4.1)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from packaging->ibmcloudsql) (2.4.7)
Collecting identify>=1.0.0
  Downloading identify-2.4.8-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 18.0 MB/s eta 0:00:01
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pre-commit->ibmcloudsql) (5.4.1)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.6.0-py2.py3-none-any.whl (21 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Requirement already satisfied: toml in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from pre-commit->ibmcloudsql) (0.10.2)
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.13.1-py2.py3-none-any.whl (8.6 MB)
     |████████████████████████████████| 8.6 MB 67.5 MB/s eta 0:00:01
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
     |████████████████████████████████| 461 kB 74.0 MB/s eta 0:00:01
Collecting filelock<4,>=3.2
  Downloading filelock-3.4.2-py3-none-any.whl (9.9 kB)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.4.1-py3-none-any.whl (14 kB)
Building wheels for collected packages: ibmcloudsql, ibm-cos-sdk, ibm-cos-sdk-core, ibm-cos-sdk-s3transfer
  Building wheel for ibmcloudsql (PEP 517) ... done
  Created wheel for ibmcloudsql: filename=ibmcloudsql-0.5.2-py3-none-any.whl size=56404 sha256=f85050fbfd04cfe0ab364d003bf646bbd46e38a2a61ab65de76247e6f3fcd756
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/45/bf/fd/549d63986d9fd05cc36d7fc532d0624c2e8e5fc3dd3b5e7cca
  Building wheel for ibm-cos-sdk (setup.py) ... done
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.10.0-py2.py3-none-any.whl size=73425 sha256=bce2ddfa668f607912cb479603918e08c9de61de81b4c8cdf4a6f6df982098a1
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/f3/a1/2e/0cffd7ccec0cb6963ec77d8473d28a7e79f3d0e4ecbf273588
  Building wheel for ibm-cos-sdk-core (setup.py) ... done
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.10.0-py2.py3-none-any.whl size=526045 sha256=155ed735675fd02ed3cbc8a9d1dc61f0e1cc1144a2250dd49828214c036f7a96
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/ce/df/1e/1da07def7155e0dd5cb2d93925ac6c0026042ecd3d3411ed9e
  Building wheel for ibm-cos-sdk-s3transfer (setup.py) ... done
  Created wheel for ibm-cos-sdk-s3transfer: filename=ibm_cos_sdk_s3transfer-2.10.0-py2.py3-none-any.whl size=88636 sha256=6fbcc1a0b8382563df111c8f90e8a2a2577621020a2f511705e1c53256e6d9f2
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/ba/16/5d/43d4b1becec01bb67c90f2a5a87263b6f7b5a2226f45bda48b
Successfully built ibmcloudsql ibm-cos-sdk ibm-cos-sdk-core ibm-cos-sdk-s3transfer
Installing collected packages: platformdirs, ibm-cos-sdk-core, filelock, distlib, virtualenv, nodeenv, identify, ibm-cos-sdk-s3transfer, cfgv, pre-commit, isodate, ibm-cos-sdk, deprecated, backoff, ibmcloudsql
  WARNING: The script virtualenv is installed in '/home/wsuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nodeenv is installed in '/home/wsuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script identify-cli is installed in '/home/wsuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pre-commit, pre-commit-validate-config and pre-commit-validate-manifest are installed in '/home/wsuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ibm-watson-machine-learning 1.0.181 requires ibm-cos-sdk==2.7.*; python_version < "3.9", but you have ibm-cos-sdk 2.10.0 which is incompatible.
Successfully installed backoff-1.10.0 cfgv-3.3.1 deprecated-1.2.13 distlib-0.3.4 filelock-3.4.2 ibm-cos-sdk-2.10.0 ibm-cos-sdk-core-2.10.0 ibm-cos-sdk-s3transfer-2.10.0 ibmcloudsql-0.5.2 identify-2.4.8 isodate-0.6.1 nodeenv-1.6.0 platformdirs-2.4.1 pre-commit-2.17.0 virtualenv-20.13.1

In [3]:
import ibmcloudsql
import sqlparse 
import pandas as pd
import getpass
import pprint
#from pixiedust.display import *
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter, Terminal256Formatter
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='vim')
apikey=''
instancecrn=''
targeturl=''

In [4]:
# 3Wa6ExXG4q-09yYaJpHHvL-EO1f4CurewID5IXRSmH8w
apikey='3Wa6ExXG4q-09yYaJpHHvL-EO1f4CurewID5IXRSmH8w'
instancecrn='crn:v1:bluemix:public:sql-query:us-south:a/ac183b33c0534bfdb3112fe7f5cb41f8:2184d60a-b8c2-4474-bb69-9f756804cead::'
targeturl = "cos://" + "us-east" + "/" + "cloud-object-storage-tf-cos-standard-swx" + "/"

# {
#  "apikey": "XSMS6DoaEru1U_RXh-e8irr4KmwIF92dspQ3W044Domu",
#  "endpoints": "https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints",
#  "iam_apikey_description": "Auto-generated for key crn:v1:bluemix:public:cloud-object-storage:global:a/ac183b33c0534bfdb3112fe7f5cb41f8:2c6fd700-a08f-4145-b271-e3a5013c0753:resource-key:fe64b947-9f22-49d4-9cc0-7dd2dc912504",
#  "iam_apikey_name": "cloud-object-storage-tf-cos-standard-swx",
#  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
#  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ac183b33c0534bfdb3112fe7f5cb41f8::serviceid:ServiceId-65af84d3-79b1-454a-acab-e52732e72b63",
#  "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/ac183b33c0534bfdb3112fe7f5cb41f8:2c6fd700-a08f-4145-b271-e3a5013c0753::"
# }

sqlClient = ibmcloudsql.SQLQuery(apikey, instancecrn, client_info='CANDEV1', target_cos_url=targeturl, max_concurrent_jobs=4, max_tries=3 )
#sqlClient.configure()  # use this if you want to change the API key or SQL Query CRN later

sqlClient.logon()

In [5]:
print('\nYour SQL Query web console link:\n')
sqlClient.sql_ui_link()

Your SQL Query web console link:

https://sql-query.cloud.ibm.com/sqlquery/?instance_crn=crn:v1:bluemix:public:sql-query:us-south:a/ac183b33c0534bfdb3112fe7f5cb41f8:2184d60a-b8c2-4474-bb69-9f756804cead::

'https://sql-query.cloud.ibm.com/sqlquery/?instance_crn=crn:v1:bluemix:public:sql-query:us-south:a/ac183b33c0534bfdb3112fe7f5cb41f8:2184d60a-b8c2-4474-bb69-9f756804cead::'

### BMO 2015-2019 CSV 1

In [30]:
sql='\
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201501.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201601.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201701.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201801.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201901.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_01.csv STORED AS CSV'

#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201501.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201601.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201701.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201801.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201901.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal" INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_01.csv STORED AS CSV

In [31]:
df1 = sqlClient.run_sql(sql)
if isinstance(df1, str):
    print(df1)
df1.head(5)

,EMPLOYERNAME,CALENDARYEAR,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,PEAKEMPLOYEECOUNT,PERMFULLTIMECOUNT,PERMPARTTIMECOUNT,TEMPCOUNT,CANADACOUNT
0,Bank of Montreal,1998,Provincial,Northwest Territories,0,NaN,30.0,NaN,NaN,NaN,NaN
1,Bank of Montreal,2017,CMA,Toronto,0,NaN,15668.0,NaN,NaN,NaN,NaN
2,Bank of Montreal,2018,CMA,Montr�al,0,NaN,3725.0,NaN,NaN,NaN,NaN
3,Bank of Montreal,2018,CMA,Edmonton,0,NaN,559.0,NaN,NaN,NaN,NaN
4,Bank of Montreal,2019,CMA,Calgary,0,NaN,779.0,NaN,NaN,NaN,NaN

In [32]:
df1.shape

(114, 11)

### BMO 2015-2019  CSV 2

In [6]:
#sql=input('Enter your SQL statement (leave empty to use a simple sample SQL)')


sql='\
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201002.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201102.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201202.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201302.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201402.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201502.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201602.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201702.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201802.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201902.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_10yrs_02.csv STORED AS CSV'
#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201002.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201102.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201202.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201302.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201402.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201502.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201602.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201702.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201802.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201902.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal" INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_10yrs_02.csv STORED AS CSV

In [7]:
#result = sqlClient.execute_sql(sql, get_result=False) 
#display(result.data)

df2 = sqlClient.run_sql(sql)
if isinstance(df2, str):
    print(df2)
df2.head(5)

,EMPLOYERNAME,CALENDARYEAR,EMPLOYMENTSTATUS,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,OCCGROUP,QUARTERID,ALLCOUNT,...,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT,SALARYRANGEBOTTOM($),SALARYRANGETOP($)
0,Bank of Montreal,2016,Full-Time,Provincial,Qu�bec,5221.0,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,2.0,408.0,...,1.0,2.0,12.0,3.0,9.0,100.0,45.0,55.0,"Under $5,000","$ 95,000 - $99,999"
1,Bank of Montreal,2016,Full-Time,CMA,Montr�al,5221.0,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,3.0,111.0,...,NaN,1.0,3.0,1.0,2.0,14.0,6.0,8.0,"Under $5,000","$ 95,000 - $99,999"
2,Bank of Montreal,2016,Part-Time,Provincial,British Columbia,5221.0,Depository Credit Intermediation,Supervisors,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$ 35,000 - $39,999","$ 35,000 - $39,999"
3,Bank of Montreal,2016,Part-Time,CMA,Montr�al,5221.0,Depository Credit Intermediation,Supervisors,2.0,13.0,...,NaN,NaN,1.0,NaN,1.0,7.0,4.0,3.0,"$ 15,000 - $19,999","$ 65,000 - $69,999"
4,Bank of Montreal,2016,Part-Time,CMA,Toronto,5221.0,Depository Credit Intermediation,Clerical Personnel,2.0,15.0,...,NaN,NaN,NaN,NaN,NaN,9.0,3.0,6.0,"$ 5,000 - $ 9,999","$ 55,000 - $59,999"

In [8]:
df2.shape

(8956, 23)

### BMO 2015-2019 CSV 3

In [36]:
sql='\
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201503.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201603.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201703.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201803.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201903.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_03.csv STORED AS CSV'

#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201503.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201603.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201703.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201803.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201903.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal" INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_03.csv STORED AS CSV

In [37]:
df3 = sqlClient.run_sql(sql)
if isinstance(df3, str):
    print(df3)
df3.head(5)

,EMPLOYERNAME,CALENDARYEAR,EMPLOYMENTSTATUS,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,SALARYRANGE($),ALLCOUNT,ALLMENCOUNT,ALLWOMENCOUNT,ABORIGALLCOUNT,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT
0,Bank of Montreal,2015,Full-Time,Provincial,British Columbia,5221.0,Depository Credit Intermediation,"$ 60,000 - $69,999",223,76.0,147.0,2.0,NaN,2.0,14.0,1.0,13.0,98.0,39.0,59.0
1,Bank of Montreal,2017,Part-Time,National,Canada,5221.0,Depository Credit Intermediation,"$ 40,000 - $49,999",103,14.0,89.0,1.0,NaN,1.0,7.0,NaN,7.0,32.0,7.0,25.0
2,Bank of Montreal,2018,Full-Time,Provincial,Nova Scotia,5221.0,Depository Credit Intermediation,"$ 35,000 - $37,499",7,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
3,Bank of Montreal,2018,Full-Time,Provincial,Alberta,5221.0,Depository Credit Intermediation,"$ 70,000 - $84,999",158,61.0,97.0,5.0,1.0,4.0,5.0,2.0,3.0,47.0,25.0,22.0
4,Bank of Montreal,2018,Full-Time,Provincial,Alberta,5221.0,Depository Credit Intermediation,"$ 85,000 - $99,999",126,57.0,69.0,4.0,3.0,1.0,8.0,2.0,6.0,33.0,22.0,11.0

In [38]:
df3.shape

(1405, 20)

### BMO 2015-2019 CSV 4

In [6]:
sql='\
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201004.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201104.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201204.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201304.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201404.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201504.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201604.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201704.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201804.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201904.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_10yrs_04.csv STORED AS CSV'

#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201004.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201104.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201204.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201304.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201404.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201504.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201604.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201704.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201804.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201904.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal" INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_10yrs_04.csv STORED AS CSV

In [7]:
df4 = sqlClient.run_sql(sql)
if isinstance(df4, str):
    print(df4)
df4.head(5)

,EMPLOYERNAME,CALENDARYEAR,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,OCCGROUP,EMPLOYMENTSTATUS,ALLCOUNT,ALLMENCOUNT,ALLWOMENCOUNT,ABORIGALLCOUNT,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT
0,Bank of Montreal,2010,Provincial,British Columbia,5221.0,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,Full-Time,42,12.0,30.0,1.0,NaN,1.0,1.0,1.0,NaN,14.0,4.0,10.0
1,Bank of Montreal,2012,Provincial,Qu�bec,5221.0,Depository Credit Intermediation,Intermediate Sales and Service Personnel,Full-Time,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bank of Montreal,2012,Provincial,New Brunswick,NaN,NaN,Overall,Full-Time,12,6.0,6.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Bank of Montreal,2014,Provincial,Ontario,5221.0,Depository Credit Intermediation,Professionals,Full-Time,843,535.0,308.0,6.0,4.0,2.0,12.0,9.0,3.0,295.0,205.0,90.0
4,Bank of Montreal,2014,Provincial,British Columbia,5221.0,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,Part-Time,3,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN

In [8]:
df4.shape

(1042, 20)

### BMO 2015-2019 CSV 5

In [9]:
sql='\
   SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201005.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201105.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201205.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201305.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201405.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201505.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201605.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201705.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201805.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201905.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_10yrs_05.csv STORED AS CSV'

#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201005.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201105.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201205.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201305.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201405.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201505.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201605.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201705.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201805.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201905.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal" INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_10yrs_05.csv STORED AS CSV

In [10]:
df5 = sqlClient.run_sql(sql)
if isinstance(df5, str):
    print(df5)
df5.head(5)

,EMPLOYERNAME,CALENDARYEAR,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,OCCGROUP,EMPLOYMENTSTATUS,TOTALPROMOTIONS,TOTALMENPROMOTIONS,...,ALLWOMENCOUNT,ABORIGALLCOUNT,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT
0,Bank of Montreal,2010,Provincial,New Brunswick,5221,Depository Credit Intermediation,Overall,Full-Time,42.0,14.0,...,26.0,3.0,NaN,3.0,2.0,1.0,1.0,3.0,NaN,3.0
1,Bank of Montreal,2010,Provincial,Newfoundland and Labrador,5221,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,Part-Time,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bank of Montreal,2014,Provincial,Saskatchewan,5221,Depository Credit Intermediation,Skilled Sales and Service Personnel,Full-Time,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
3,Bank of Montreal,2016,Provincial,Qu�bec,5221,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,Full-Time,NaN,NaN,...,96.0,1.0,1.0,NaN,4.0,1.0,3.0,39.0,19.0,20.0
4,Bank of Montreal,2016,Provincial,Qu�bec,5221,Depository Credit Intermediation,Supervisors,Part-Time,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0

In [11]:
df5.shape

(1034, 32)

### BMO CSV 6

In [6]:
sql='\
   SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201006.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201106.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201206.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201306.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201406.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201506.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201606.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201706.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201806.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    UNION \
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/201906.csv STORED AS CSV \
    WHERE EMPLOYERNAME = "Bank of Montreal" \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_10yrs_06.csv STORED AS CSV'

#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201006.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201106.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201206.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201306.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201406.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201506.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201606.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201706.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201806.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal"
UNION
SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/201906.csv STORED AS CSV
WHERE EMPLOYERNAME = "Bank of Montreal" INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_10yrs_06.csv STORED AS CSV

In [7]:
df6 = sqlClient.run_sql(sql)
if isinstance(df6, str):
    print(df6)
df6.head(5)

,EMPLOYERNAME,CALENDARYEAR,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,OCCGROUP,EMPLOYMENTSTATUS,ALLCOUNT,ALLMENCOUNT,ALLWOMENCOUNT,ABORIGALLCOUNT,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT
0,Bank of Montreal,2010,Provincial,Ontario,5221.0,Depository Credit Intermediation,Intermediate Sales and Service Personnel,Full-Time,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bank of Montreal,2012,Provincial,Ontario,5221.0,Depository Credit Intermediation,Senior Managers,Full-Time,5,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
2,Bank of Montreal,2013,National,Canada,5221.0,Depository Credit Intermediation,Other Manual Workers,Full-Time,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bank of Montreal,2013,Provincial,Saskatchewan,5221.0,Depository Credit Intermediation,Clerical Personnel,Part-Time,13,1.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0
4,Bank of Montreal,2014,Provincial,Nova Scotia,5221.0,Depository Credit Intermediation,Skilled Sales and Service Personnel,Part-Time,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df6.shape

(1185, 20)

In [45]:
dfs = [df1,df2,df3,df4,df5]
for i in range(5):
    print(f"BMO csv{i+1} has shape {dfs[i].shape}")

BMO csv1 has shape (114, 11)
BMO csv2 has shape (4706, 23)
BMO csv3 has shape (1405, 20)
BMO csv4 has shape (554, 20)
BMO csv5 has shape (525, 32)

### df2

In [54]:
df2.CALENDARYEAR.value_counts(), df2.shape

(2016    978
 2015    962
 2017    958
 2018    930
 2019    878
 Name: CALENDARYEAR, dtype: int64,
 (4706, 23))

In [51]:
df2.head()

,EMPLOYERNAME,CALENDARYEAR,EMPLOYMENTSTATUS,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,OCCGROUP,QUARTERID,ALLCOUNT,...,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT,SALARYRANGEBOTTOM($),SALARYRANGETOP($)
0,Bank of Montreal,2018,Full-Time,Provincial,Saskatchewan,5221.0,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,"$ 5,000 - $ 9,999","$ 75,000 - $79,999"
1,Bank of Montreal,2018,Full-Time,CMA,Calgary,5221.0,Depository Credit Intermediation,Middle and Other Managers,2.0,25.0,...,NaN,NaN,NaN,NaN,NaN,5.0,3.0,2.0,"Under $5,000","$100,000 and over"
2,Bank of Montreal,2018,Full-Time,CMA,Halifax,5221.0,Depository Credit Intermediation,Intermediate Sales and Service Personnel,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$ 30,000 - $34,999","$ 50,000 - $54,999"
3,Bank of Montreal,2019,Full-Time,National,Canada,5221.0,Depository Credit Intermediation,Skilled Sales and Service Personnel,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Under $5,000","$100,000 and over"
4,Bank of Montreal,2019,Full-Time,Provincial,New Brunswick,NaN,NaN,Overall,NaN,137.0,...,NaN,2.0,12.0,5.0,7.0,7.0,3.0,4.0,NaN,NaN

In [55]:
df2.columns

Index(['EMPLOYERNAME', 'CALENDARYEAR', 'EMPLOYMENTSTATUS', 'GEOGRAPHY',
       'LOCATION', 'NAICSID', 'NAICSCLASSTITLE', 'OCCGROUP', 'QUARTERID',
       'ALLCOUNT', 'ALLMENCOUNT', 'ALLWOMENCOUNT', 'ABORIGALLCOUNT',
       'ABORIGMENCOUNT', 'ABORIGWOMENCOUNT', 'PWDALLCOUNT', 'PWDMENCOUNT',
       'PWDWOMENCOUNT', 'VISMINALLCOUNT', 'VISMINMENCOUNT', 'VISMINWOMENCOUNT',
       'SALARYRANGEBOTTOM($)', 'SALARYRANGETOP($)'],
      dtype='object')

In [48]:
df3.CALENDARYEAR.value_counts()

2015    286
2016    283
2018    281
2019    280
2017    275
Name: CALENDARYEAR, dtype: int64

In [49]:
df4.CALENDARYEAR.value_counts()

2015    120
2019    113
2016    110
2017    108
2018    103
Name: CALENDARYEAR, dtype: int64

In [50]:
df5.CALENDARYEAR.value_counts()

2018    111
2015    106
2019    104
2017    103
2016    101
Name: CALENDARYEAR, dtype: int64

In [56]:
df1.CALENDARYEAR.value_counts()

2015    23
2017    23
2018    23
2019    23
1998    22
Name: CALENDARYEAR, dtype: int64

In [7]:
sql='\
    SELECT * FROM cos://us-east/cloud-object-storage-tf-cos-standard-swx/BMO_10yrs_05.csv STORED AS CSV \
    INTO cos://us-east/cloud-object-storage-tf-cos-standard-swx/test1.csv STORED AS CSV'

#if " INTO " not in sql:
#sql += ' INTO {}myQueryResult STORED AS CSV'.format(targeturl)

formatted_sql = sqlparse.format(sql, reindent=True, indent_tabs=True, keyword_case='upper')
lexer = get_lexer_by_name("sql", stripall=True)
formatter = Terminal256Formatter(style='tango')
result = highlight(formatted_sql, lexer, formatter)
from IPython.core.display import display, HTML
print('\nYour SQL statement is:\n')
print(result)

Your SQL statement is:

SELECT *
FROM cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/BMO_10yrs_05.csv STORED AS CSV INTO cos://us-east/cloud-OBJECT-
STORAGE-tf-cos-standard-swx/test1.csv STORED AS CSV

In [8]:
dff = sqlClient.run_sql(sql)
if isinstance(dff, str):
    print(dff)
dff.head(5)

,EMPLOYERNAME,CALENDARYEAR,GEOGRAPHY,LOCATION,NAICSID,NAICSCLASSTITLE,OCCGROUP,EMPLOYMENTSTATUS,TOTALPROMOTIONS,TOTALMENPROMOTIONS,...,ABORIGALLCOUNT,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT,jobid
0,Bank of Montreal,2010,Provincial,New Brunswick,5221,Depository Credit Intermediation,Overall,Full-Time,42.0,14.0,...,3.0,NaN,3.0,2.0,1.0,1.0,3.0,NaN,3.0,52c95e7d-4a4a-494a-9eb6-fe9372c42896
1,Bank of Montreal,2010,Provincial,Newfoundland and Labrador,5221,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,Part-Time,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52c95e7d-4a4a-494a-9eb6-fe9372c42896
2,Bank of Montreal,2014,Provincial,Saskatchewan,5221,Depository Credit Intermediation,Skilled Sales and Service Personnel,Full-Time,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,52c95e7d-4a4a-494a-9eb6-fe9372c42896
3,Bank of Montreal,2016,Provincial,Qu�bec,5221,Depository Credit Intermediation,Administrative and Senior Clerical Personnel,Full-Time,NaN,NaN,...,1.0,1.0,NaN,4.0,1.0,3.0,39.0,19.0,20.0,52c95e7d-4a4a-494a-9eb6-fe9372c42896
4,Bank of Montreal,2016,Provincial,Qu�bec,5221,Depository Credit Intermediation,Supervisors,Part-Time,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,52c95e7d-4a4a-494a-9eb6-fe9372c42896

In [9]:
dfff = dff[(dff.OCCGROUP == 'Overall') & (dff.GEOGRAPHY == 'National')].groupby(['CALENDARYEAR']).sum()
dfff1 = dfff.iloc[:, -12:]

In [10]:
dfff1

,ALLCOUNT,ALLMENCOUNT,ALLWOMENCOUNT,ABORIGALLCOUNT,ABORIGMENCOUNT,ABORIGWOMENCOUNT,PWDALLCOUNT,PWDMENCOUNT,PWDWOMENCOUNT,VISMINALLCOUNT,VISMINMENCOUNT,VISMINWOMENCOUNT
CALENDARYEAR,,,,,,,,,,,,
2010,5146,1941.0,3205.0,88.0,20.0,68.0,96.0,35.0,61.0,1896.0,819.0,1077.0
2011,6179,2459.0,3720.0,83.0,30.0,53.0,113.0,51.0,62.0,2445.0,1111.0,1334.0
2012,4157,1714.0,2443.0,59.0,21.0,38.0,97.0,44.0,53.0,1697.0,777.0,920.0
2013,3184,1278.0,1906.0,63.0,16.0,47.0,83.0,38.0,45.0,1182.0,545.0,637.0
2014,4045,1679.0,2366.0,49.0,9.0,40.0,108.0,45.0,63.0,1581.0,734.0,847.0
2015,3798,1630.0,2168.0,55.0,9.0,46.0,113.0,41.0,72.0,1528.0,725.0,803.0
2016,3689,1586.0,2103.0,47.0,12.0,35.0,129.0,48.0,81.0,1349.0,652.0,697.0
2017,3948,1800.0,2148.0,46.0,15.0,31.0,117.0,46.0,71.0,1638.0,821.0,817.0
2018,5658,2068.0,3590.0,108.0,22.0,86.0,220.0,51.0,169.0,2044.0,906.0,1138.0
2019,3705,1612.0,2093.0,35.0,12.0,23.0,149.0,49.0,100.0,1521.0,705.0,816.0

In [26]:
from project_lib import Project
project = Project(project_id='91943081-ed45-4d8f-bea5-204a7508b023', project_access_token='p-775a1039ad1b8858ade6954c8e0514fde9fd4369')
pc = project.project_context

project.save_data(data=dfff1.to_csv(index=False),file_name='ForGrace1.csv',overwrite=True)

{'file_name': 'ForGrace1.csv',
 'message': 'File saved to project storage.',
 'bucket_name': 'candev-donotdelete-pr-2gh0yai1vcsvoh',
 'asset_id': '677aade3-1a48-4427-a7b7-58413c780126'}